name: my-check

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.14]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.14
        uses: actions/setup-node@v1
        with:
          node-version: 15.14

      - name: npm install, build
        run: |
          make install
          make build
        env:
          CI: true

      - name: Run linter
        run: make lint

#      - name: Run tests
#        run: make test
